academy/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('courses/',views.Courses, name='courses'),  
    path('trainers/',views.Trainers, name='trainers'),  
    path('students/',views.Students, name='students'),
    path('course/detail/<int:id>',views.course_detail,name="course_detail"),
    path('course/edit/<int:id>',views.course_edit,name="edit_course"),
    path('course/delete/<int:id>',views.course_delete,name="delete_course"),
    path('trainer/detail/<int:id>',views.trainer_detail,name="trainer_detail"),
    path('trainer/edit/<int:id>',views.trainer_edit,name="trainer_edit"),
    path('trainer/delete/<int:id>',views.trainer_delete,name="trainer_delete"),
    path('student/detail/<int:id>',views.student_detail,name="student_detail"),
    path('student/edit/<int:id>',views.student_edit,name="student_edit"),
    path('student/delete/<int:id>',views.student_delete,name="student_delete"),
    path('student/add',views.student_add,name='student_add'),
    path('trainer/add',views.trainer_add,name="trainer_add"),
    path('course/add',views.course_add,name="course_add"),
]

training_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from academy import urls
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('academy/', include('academy.urls')),  
    path('',views.Home,name='home'),
    path('accounts/',include('accounts.urls')) 
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

academy/models.py
from django.db import models

# Create your models here.
class Course(models.Model):
    course_name = models.CharField(max_length=100)
    description = models.TextField()
    duration = models.IntegerField(help_text="Duration in weeks")
    course_image = models.ImageField(upload_to = 'Course/')

    def __str__(self):
        return f"{self.course_name}"


class Trainer(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    expertise = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True, blank=True, help_text="Python, Django, Data Science")
    trainer_picture = models.ImageField(upload_to = 'Trainer/')

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def full_Name(self):
        return f"{self.first_name} {self.last_name}"



class Student(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    is_active = models.BooleanField(default=True)
    enrolled_courses = models.ForeignKey(Course, on_delete = models.SET_NULL, null=True, blank=True)
    trainer = models.ForeignKey(Trainer, on_delete = models.SET_NULL, null=True, blank=True)
    

    
    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def full_name(self):
        return f"{self.first_name} {self.last_name}"
    

templates/add_course.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Course</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
</head>

<body>
   <h1>Add Course</h1>
   <form action="{% url 'course_add' %}" method="POST" enctype="multipart/form-data" class="w-50" style="margin: auto;">
       {{form | crispy }}
    {% csrf_token %}

      <button type="submit">Submit</button>
   </form>
 
</body>

</html>

templates/add_student.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Student</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
</head>

<body>
   <h1>Add Student</h1>
   <form action="{% url 'student_add' %}" method="POST" enctype="multipart/form-data" class="w-50" style="margin: auto;">
       {{form | crispy }}
    {% csrf_token %}

      <button type="submit">Submit</button>
   </form>
 
</body>

</html>

templates/add_trainer.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Trainer</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
</head>

<body>
   <h1>Add trainer</h1>
   <form action="{% url 'trainer_add' %}" method="POST" enctype="multipart/form-data" class="w-50" style="margin: auto;">
       {{form | crispy }}
    {% csrf_token %}

      <button type="submit">Submit</button>
   </form>
 
</body>

</html>

templates/course_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Course Detail</title>
</head>
<body>
    <h2>Course {{course.course_name}}</h2>
</body>
</html>

templates/courses.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Courses Offered</title>
        <link rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">

        <!-- Bootstrap CSS -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css"
            rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/style1.css' %}">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">

                <a class="navbar-brand" href="/">Navbar</a>

                <button class="navbar-toggler" type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Navbar Items -->
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav ms-auto">

                        <li class="nav-item">
                            <a class="nav-link active" href="/">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link active"
                                href="/academy/courses/">Courses</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link active"
                                href="/academy/trainers/">Trainers</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link active"
                                href="/academy/students/">Students</a>
                        </li>

                        {% if not user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link active"
                                href="/accounts/register/">Register</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link active"
                                href="/accounts/login/">Login</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link active "
                                href="/accounts/logout/">Logout</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>

            </div>
        </nav>

        <h1>Courses Offered</h1>
        {% if perms.academy.add_student %}
        <a href="{% url 'student_add' %}">Add Student</a>
        {% endif %}

        <table>
            <thead>
                <tr>
                    <th>Course Name</th>
                    <th>Duration (weeks)</th>
                    <th>Description</th>
                    <th>Image</th>
                    <th>View</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for course in Courses %}
                <tr>
                    <td>{{ course.course_name }}</td>
                    <td>{{ course.duration }}</td>
                    <td>{{ course.description }}</td>
                    <td><img src="{{ course.course_image.url }}"
                            alt="{{ course.course_name }}"
                            style="width:100px; height:auto;"></td>
                    <td>
                        <div>
                            <a href="{% url 'course_detail' course.id %}"><i
                                    class="fa fa-eye"></i></a>
                        </div>
                    </td>
                    <td>
                        <div>
                            <a href="{% url 'edit_course' course.id %}"><i
                                    class="fa fa-edit"></i></a>
                        </div>
                    </td>
                    <td>
                        <div>
                            <a href="{% url 'delete_course' course.id %}"><i
                                    class="fa fa-trash"></i></a>
                        </div>
                    </td>
                </tr>

                {% endfor %}
            </tbody>
        </table>

    </body>
</html>

templates/edit_student.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Course</title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Optional external CSS -->
    <link rel="stylesheet" href="{% static 'css/style1.css' %}">
</head>

<body class="bg-light">

    <div class="container mt-5">

        <div class="card shadow p-4">

            <h2 class="mb-4">Edit Student</h2>

            <form action="{% url 'student_edit' student.id %}" method="POST" enctype="multipart/form-data">

                {% csrf_token %}
                {{ form|crispy }}

                <button type="submit" class="btn btn-primary mt-3">
                    Update
                </button>
            </form>

        </div>
    </div>


</body>
</html>

templates/edit_trainer.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Course</title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Optional external CSS -->
    <link rel="stylesheet" href="{% static 'css/style1.css' %}">
</head>

<body class="bg-light">

    <div class="container mt-5">

        <div class="card shadow p-4">

            <h2 class="mb-4">Edit Trainer</h2>

            <form action="{% url 'trainer_edit' trainer.id %}" method="POST" enctype="multipart/form-data">

                {% csrf_token %}
                {{ form|crispy }}

                <button type="submit" class="btn btn-primary mt-3">
                    Update
                </button>
            </form>

        </div>
    </div>


</body>
</html>

templates/student_detail.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Student Detail</title>
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css"
            rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/style1.css' %}">

    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">

                <a class="navbar-brand" href="/">Navbar</a>

                <button class="navbar-toggler" type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Navbar Items -->
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav ms-auto">

                        <li class="nav-item">
                            <a class="nav-link active" href="/">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link active"
                                href="/academy/courses/">Courses</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link active"
                                href="/academy/trainers/">Trainers</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link active"
                                href="/academy/students/">Students</a>
                        </li>

                        {% if not user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link active"
                                href="/accounts/register/">Register</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link active"
                                href="/accounts/login/">Login</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link active "
                                href="/accounts/logout/">Logout</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>

            </div>
        </nav>
        <!-- Gradient Header -->
        <div class="py-4 text-white"
            style="background: linear-gradient(to right, #647dee, #7f53ac);">
            <div class="container">
                <h2 class="m-0">{{ student.name }} – Details</h2>
            </div>
        </div>

        <!-- Content -->
        <div class="container my-5">
            <div class="card shadow p-4">

                <!-- Name -->
                <div class="mb-3">
                    <h5 class="fw-bold">Name</h5>
                    <p class="text-muted">{{ student.full_name }}</p>
                </div>

                <!-- Email -->
                <div class="mb-3">
                    <h5 class="fw-bold">Email</h5>
                    <p class="text-muted">{{ student.email }}</p>
                </div>

                <!-- Active -->
                <div class="mb-3">
                    <h5 class="fw-bold">Active</h5>
                    <p class="text-muted">{{ student.is_active }}</p>
                </div>

                <!-- Enrolled Courses -->
                <div class="mb-3">
                    <h5 class="fw-bold">Enrolled Courses</h5>
                    <p class="text-muted">{{ student.enrolled_courses }}</p>
                </div>

                <!-- Trainer -->
                <div class="mb-3">
                    <h5 class="fw-bold">Trainer</h5>
                    <p class="text-muted">{{ student.trainer }}</p>
                </div>

                {% if perms.academy.view_student %}
                <a href="{% url 'students' %}" class="btn btn-primary">← Back to
                    Students</a>
                {% endif %}
            </div>
        </div>

    </body>
</html>

templates/students.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Students</title>
        <link rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">

        <!-- Bootstrap CSS -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css"
            rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/style1.css' %}">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">

                <a class="navbar-brand" href="/">Navbar</a>

                <button class="navbar-toggler" type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Navbar Items -->
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav ms-auto">

                        <li class="nav-item">
                            <a class="nav-link active" href="/">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link active"
                                href="/academy/courses/">Courses</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link active"
                                href="/academy/trainers/">Trainers</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link active"
                                href="/academy/students/">Students</a>
                        </li>

                        {% if not user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link active"
                                href="/accounts/register/">Register</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link active"
                                href="/accounts/login/">Login</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link active "
                                href="/accounts/logout/">Logout</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>

            </div>
        </nav>

        <h1>Students</h1>
        {% if perms.academy.add_student %}
        <a href="{% url 'student_add' %}">Add Student</a>
        {% endif %}

        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Active</th>
                    <th>Enrolled Courses</th>
                    <th>Trainer</th>
                    {% if perms.academy.view_student %}
                    <th>View</th>
                    {% endif %}
                    {% if perms.academy.change_student %}

                    <th>Edit</th>
                    {% endif %}
                    {% if perms.academy.delete_student %}

                    <th>Delete</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for student in Students %}
                <tr>
                    <td>{{ student.full_name }}</td>
                    <td>{{ student.email }}</td>
                    <td>{{ student.is_active }}</td>
                    <td>{{ student.enrolled_courses }}</td>
                    <td>{{ student.trainer }}</td>
                    {% if perms.academy.view_student %}
                    <td>
                        <div>
                            <a href="{% url 'student_detail' student.id %}"><i
                                    class="fa fa-eye"></i></a>
                        </div>
                    </td>
                    {% endif %}

                    {% if perms.academy.change_student %}
                    <td>
                        <div>
                            <a href="{% url 'student_edit' student.id %}"><i
                                    class="fa fa-edit"></i></a>
                        </div>
                    </td>
                    {% endif %}

                    {% if perms.academy.delete_student %}
                    <td>
                        <div>
                            <a href="{% url 'student_delete' student.id %}"><i
                                    class="fa fa-trash"></i></a>
                        </div>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>

    </body>
</html>

templates/trainer_detail.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Trainer Detail</title>
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css"
            rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/style1.css' %}">

    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">

                <a class="navbar-brand" href="/">Navbar</a>

                <button class="navbar-toggler" type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Navbar Items -->
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav ms-auto">

                        <li class="nav-item">
                            <a class="nav-link active" href="/">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link active"
                                href="/academy/courses/">Courses</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link active"
                                href="/academy/trainers/">Trainers</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link active"
                                href="/academy/students/">Students</a>
                        </li>

                        {% if not user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link active"
                                href="/accounts/register/">Register</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link active"
                                href="/accounts/login/">Login</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link active "
                                href="/accounts/logout/">Logout</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>

            </div>
        </nav>

        <!-- HEADER BAR SIMILAR TO YOUR TABLE -->
        <div class="bg-primary bg-gradient text-white py-4 px-4 mb-4">
            <h2 class="m-0">Trainer Details</h2>
        </div>

        <div class="container">

            <div class="card shadow p-4">

                <!-- Name -->
                <div class="mb-3">
                    <h5 class="fw-bold">Name</h5>
                    <p class="text-muted">{{ trainer.full_Name }}</p>
                </div>

                <!-- Email -->
                <div class="mb-3">
                    <h5 class="fw-bold">Email</h5>
                    <p class="text-muted">{{ trainer.email }}</p>
                </div>

                <!-- Expertise -->
                <div class="mb-3">
                    <h5 class="fw-bold">Expertise</h5>
                    <p class="text-muted">{{ trainer.expertise }}</p>
                </div>

                <!-- Profile Image -->
                <div class="mb-3">
                    <h5 class="fw-bold">Profile Picture</h5>

                    <img src="{{ trainer.trainer_picture.url }}"
                        class="img-thumbnail rounded"
                        style="max-width:200px;">

                </div>
                {% if perms.academy.view_trainer %}

                <a href="{% url 'trainers' %}" class="btn btn-primary mt-3">←
                    Back to Trainers</a>
                {% endif %}
            </div>
        </div>

    </body>
</html>

templates/trainers.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Trainers</title>
        <link rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">

        <!-- Bootstrap CSS -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css"
            rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/style1.css' %}">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">

                <a class="navbar-brand" href="/">Navbar</a>

                <button class="navbar-toggler" type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Navbar Items -->
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav ms-auto">

                        <li class="nav-item">
                            <a class="nav-link active" href="/">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link active"
                                href="/academy/courses/">Courses</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link active"
                                href="/academy/trainers/">Trainers</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link active"
                                href="/academy/students/">Students</a>
                        </li>

                        {% if not user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link active"
                                href="/accounts/register/">Register</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link active"
                                href="/accounts/login/">Login</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link active "
                                href="/accounts/logout/">Logout</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>

            </div>
        </nav>
        <h1>Trainers</h1>
        {% if perms.academy.add_student %}
        <a href="{% url 'student_add' %}">Add Student</a>
        {% endif %}
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Expertise</th>
                    <th>Profile Pic</th>
                    <th>View</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for trainer in Trainers %}
                <tr>
                    <td>{{trainer.full_Name}}</td>
                    <td>{{trainer.email}}</td>
                    <td>{{trainer.expertise}}</td>
                    <td><img src="{{ trainer.trainer_picture.url }}"
                            alt="{{ trainer.full_Name }}"
                            style="width:100px; height:auto;"></td>
                    <td>
                        <div>
                            <a href="{% url 'trainer_detail' trainer.id %}"><i
                                    class="fa fa-eye"></i></a>
                        </div>
                    </td>
                    <td>
                        <div>
                            <a href="{% url 'trainer_edit' trainer.id %}"><i
                                    class="fa fa-edit"></i></a>
                        </div>
                    </td>
                    <td>
                        <div>
                            <a href="{%  url 'trainer_delete' trainer.id %}"><i
                                    class="fa fa-trash"></i></a>
                        </div>

                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        </body>
    </html>